title: Think-Aloud
description: "A small notebook of number and ideas, postcards, and quiet words."

# Use GitHub Pages' built-in Minimal theme
theme: jekyll-theme-minimal

# Optional extras
markdown: kramdown
highlighter: rouge

