title: Think-Aloud
description: "A small notebook of number and ideas, postcards, and quiet words."
theme: jekyll-theme-minimal

# IMPORTANT for GitHub project pages:
url: "https://thinkaloud2024.github.io"
baseurl: "/Think-Aloud"

markdown: kramdown
highlighter: rouge
